[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "youtube-search-downloader"
version = "1.0.0"
description = "Cross-platform terminal YouTube search and downloader"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "yt-dlp>=2026.1.0",
    "imageio-ffmpeg>=0.6.0"
]


[project.scripts]
youtube-downloader = "youtube_downloader.ui:start"


[tool.setuptools.packages.find]
include = ["youtube_downloader*"]
